theme: jekyll-theme-minimal
title: Mohammed Amine Bennouna
description: PhD Candidate in Operations Research - MIT Operations Research Center
logo: https://mohammedamine-bennouna.github.io/Remise-des-prix-X.JPG	
