theme: jekyll-theme-minimal
title: Mohammed Amine Bennouna
description: Third year student at Ecole Polytechnique - Applied Mathematics mohammed-amine.bennouna@polytechnique.edu
logo: https://mohammedamine-bennouna.github.io/Yeah.jpg
